apiVersion: v1
kind: Secret
metadata:
  name: homepage-config
  annotations:
    kubernetes.io/service-account.name: {{ include "homepage.serviceAccountName" $ }}
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
data:
  {{- .Values.config | toYaml | nindent 2 }}
